name: Unit Tests JDK 21 Linux 64 (disk)
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    name: Unit-Tests-JDK-21-Windows-x64-Disk
    runs-on: windows-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.ORGANIZATION_WORKFLOWS_APP_ID }}
          private-key: ${{ secrets.ORGANIZATION_WORKFLOWS_APP_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Build with maven
        run: mvn `-Dyoutrackdb.test.env=ci -B package --file pom.xml
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v5
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}