name: Branch Unit Tests and Deployment
on:
  push:
    branches: [ "develop" ]
jobs:
  JDK-21-Windows-ARM-Disk:
    name: Unit Tests on JDK 21 Windows ARM (Disk)
    runs-on: windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -Dyoutrackdb.test.env=ci -B package --file pom.xml
  JDK-21-Windows-x64-Disk:
    name: Unit Tests on JDK 21 Windows x64 (Disk)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn `-Dyoutrackdb.test.env=ci -B package --file pom.xml
  JDK-21-Linux-x64-Disk:
    name: Unit Tests on JDK 21 Ubuntu x64 (Disk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -Dyoutrackdb.test.env=ci -B package --file pom.xml
  deploy:
    name: Deployment to maven repository
    runs-on: ubuntu-latest
    needs: [ JDK-21-Windows-ARM-Disk, JDK-21-Linux-x64-Disk, JDK-21-Windows-x64-Disk ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: central-portal-snapshots
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
      - name: Deploy SHA prefixed version with maven
        run: mvn -Dsha1=-${{ env.COMMIT_SHORT_SHA }} -DskipTests=true -B deploy --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      - name: Deploy snapshot with maven
        run: mvn -DskipTests=true -B deploy --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      - name: Deploy YTDB console to the docker hub
        run: mvn -pl console -am -Ddocker.username=youtrackdb -Ddocker.password=${{ secrets.DOCKER_PASSWORD }} -Dsha1=-${{ env.COMMIT_SHORT_SHA }} -DdockerImages=true -DskipTests=true -Ddocker.tags.latest=latest -B clean deploy --file pom.xml