name: Unit Tests for PR
on:
  push:
    branches: [ "develop" ]
jobs:
  JDK-21-Linux-ARM-Disk:
    name: Unit Tests on Mac ARM (Disk)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -Dyoutrackdb.test.env=ci -B package --file pom.xml
  JDK-21-Windows-x64-Disk:
    name: Unit Tests on JDK 21 Windows x64 (Disk)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn `-Dyoutrackdb.test.env=ci -B package --file pom.xml
  JDK-21-Linux-x64-Disk:
    name: Unit Tests on JDK 21 Linux x64 (Disk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -Dyoutrackdb.test.env=ci -B package --file pom.xml
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v5
  deploy:
    name: Deployment to maven repository
    runs-on: ubuntu-latest
    needs: [JDK-21-Linux-ARM-Disk, JDK-21-Linux-x64-Disk, JDK-21-Windows-x64-Disk]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: space-youtrackdb-daily
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build with maven
        run: mvn -DskipTests=true -B deploy --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.SPACE_USER_NAME }}
          MAVEN_PASSWORD: ${{ secrets.SPACE_REPO_PASSWORD }}