name: Unit Tests for PR
on:
  pull_request:
    branches: [ "develop" ]
jobs:
  JDK-21-Mac-ARM-Memory:
    name: Unit Tests on JDK 21 Mac ARM (Memory)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -B package --file pom.xml
  JDK-21-Windows-x64-Memory:
    name: Unit Tests on JDK 21 Windows x64 (Memory)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -B package --file pom.xml
  JDK-21-Linux-x64-Disk:
    name: Unit Tests on JDK 21 Linux x64 (Disk)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -Dyoutrackdb.test.env=ci -B package --file pom.xml